name: pvtro_common
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none" 
environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  slang: ^4.8.1
  slang_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.8.0
  slang_build_runner: ^4.8.1
