name: pvtrl
description: "pathverse translation lite"
version: 0.0.2
homepage: https://pathverse.com
repository: https://github.com/pathverse/flutter_gloveboxes

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  slang: ">=4.8.0 <5.0.0"
  slang_flutter: ">=4.8.0 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ">=2.5.0 <3.0.0"
  slang_build_runner: ">=4.8.0 <5.0.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
