name: pvlogger
description: "A powerful and flexible logging utility for Dart applications"
version: 0.9.0
homepage: https://github.com/Pathverse/flutter_gloveboxes

environment:
  sdk: ^3.9.2

dependencies:
  # Pure Dart package with no external dependencies

dev_dependencies:
  test: ^1.24.0
  lints: ^5.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
