name: pvcache
description: "A library that builds on top of Hive to provide additional adapters and secure storage options."
version: 0.1.0
homepage: https://github.com/Pathverse/flutter_gloveboxes

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  hive_ce: ">=2.11.0 <3.0.0"
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
