name: pvcache
description: "A new Flutter package project."
version: 0.0.1
homepage: https://flutter.dev

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  hive_ce: ">=2.11.0 <3.0.0"
  flutter_secure_storage: ">=9.2.0 <10.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
