name: Auto PR Merge to release/aws-amplify

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-auto-pr]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log trigger source
        run: |
          echo "Workflow triggered by: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            echo "Triggered from repository: ${{ github.event.client_payload.repository }}"
            echo "Ref: ${{ github.event.client_payload.ref }}"
            echo "SHA: ${{ github.event.client_payload.sha }}"
          fi

      - name: Check if release/aws-amplify branch exists
        id: check-branch
        run: |
          if git ls-remote --heads origin release/aws-amplify | grep -q release/aws-amplify; then
            echo "branch_exists=true" >> $GITHUB_OUTPUT
          else
            echo "branch_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create release/aws-amplify branch if it doesn't exist
        if: steps.check-branch.outputs.branch_exists == 'false'
        run: |
          git checkout -b release/aws-amplify
          git push origin release/aws-amplify
          echo "Created release/aws-amplify branch from main"

      - name: Check for differences between branches
        id: check-diff
        if: steps.check-branch.outputs.branch_exists == 'true'
        run: |
          git fetch origin release/aws-amplify
          DIFF_COUNT=$(git rev-list --count origin/release/aws-amplify..origin/main)
          echo "diff_count=$DIFF_COUNT" >> $GITHUB_OUTPUT
          echo "Commits ahead: $DIFF_COUNT"

      - name: Check if PR already exists
        id: check-pr
        if: steps.check-branch.outputs.branch_exists == 'true' && steps.check-diff.outputs.diff_count != '0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_EXISTS=$(gh pr list --base release/aws-amplify --head main --state open --json number --jq length)
          echo "pr_exists=$PR_EXISTS" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: create-pr
        if: steps.check-branch.outputs.branch_exists == 'true' && steps.check-diff.outputs.diff_count != '0' && steps.check-pr.outputs.pr_exists == '0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL=$(gh pr create \
            --base release/aws-amplify \
            --head main \
            --title "🚀 Auto-sync: flutter_gloveboxes main → release/aws-amplify" \
            --body "Auto-sync flutter_gloveboxes changes from main to release/aws-amplify for deployment." \
            --label "automated,deployment")
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT

      - name: Auto-approve and merge PR
        if: steps.check-branch.outputs.branch_exists == 'true' && steps.check-diff.outputs.diff_count != '0' && steps.check-pr.outputs.pr_exists == '0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get PR number from URL
          PR_NUMBER=$(echo "${{ steps.create-pr.outputs.pr_url }}" | sed 's/.*\/pull\///')
          
          # Approve the PR
          gh pr review $PR_NUMBER --approve --body "Auto-approved: Automated sync from main to release branch"
          
          # Enable auto-merge with squash
          gh pr merge $PR_NUMBER --auto --squash --delete-branch

      - name: No changes to sync
        if: steps.check-branch.outputs.branch_exists == 'true' && steps.check-diff.outputs.diff_count == '0'
        run: |
          echo "No commits between release/aws-amplify and main. No PR needed."

      - name: PR already exists
        if: steps.check-branch.outputs.branch_exists == 'true' && steps.check-diff.outputs.diff_count != '0' && steps.check-pr.outputs.pr_exists != '0'
        run: |
          echo "PR already exists from main to release/aws-amplify. Skipping creation."
