name: pv_assetbuilder_test
description: Comprehensive test and demonstration app for PV Asset Builder custom load methods.
publish_to: none
version: 0.1.1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  pv_assetbuilder:
    path: ../pv_assetbuilder
  pv_assetprovider:
    path: ../pv_assetprovider
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
flutter:
  assets:
    - assets/config/
    - assets/test/
    - assets/test2/
    - data/
    - images/
    - assets/web/
  uses-material-design: true
